# fly.toml generated for hand-and-brain WebSocket server
# This config deploys only the ws server at server/ws-server.js
# It exposes HTTP/HTTPS and supports WebSocket upgrades automatically.

app = "hand-and-brain-ws"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 400

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/health"
    protocol = "http"
    grace_period = "10s"

